// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABdA3JjVC0lKmYJCfWQJ92brFF1-IkAjY',
    appId: '1:946989285510:web:b7d39eba4f46b98ace1107',
    messagingSenderId: '946989285510',
    projectId: 'shoppingapp-d5f73',
    authDomain: 'shoppingapp-d5f73.firebaseapp.com',
    storageBucket: 'shoppingapp-d5f73.firebasestorage.app',
    measurementId: 'G-2WVKHKWMM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgUOlj2v2FeIqfzqahokzj3N0C6F2_N_A',
    appId: '1:946989285510:android:5509631dae189aabce1107',
    messagingSenderId: '946989285510',
    projectId: 'shoppingapp-d5f73',
    storageBucket: 'shoppingapp-d5f73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMICUnStZ4wi7YPpIRnoffZTbxOPdmQMc',
    appId: '1:946989285510:ios:d85f991beb735466ce1107',
    messagingSenderId: '946989285510',
    projectId: 'shoppingapp-d5f73',
    storageBucket: 'shoppingapp-d5f73.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMICUnStZ4wi7YPpIRnoffZTbxOPdmQMc',
    appId: '1:946989285510:ios:d85f991beb735466ce1107',
    messagingSenderId: '946989285510',
    projectId: 'shoppingapp-d5f73',
    storageBucket: 'shoppingapp-d5f73.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABdA3JjVC0lKmYJCfWQJ92brFF1-IkAjY',
    appId: '1:946989285510:web:9df36cb50b690538ce1107',
    messagingSenderId: '946989285510',
    projectId: 'shoppingapp-d5f73',
    authDomain: 'shoppingapp-d5f73.firebaseapp.com',
    storageBucket: 'shoppingapp-d5f73.firebasestorage.app',
    measurementId: 'G-NSBSWJDFD8',
  );
}
